version: '3.8'

services:
  medical-rag:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=localhost
      - CHROMA_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./chroma_data:/app/chroma_data
      - ./data:/app/data
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma:0.5.18
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
    volumes:
      - ./chroma_data:/chroma/chroma
    command: ["--host", "0.0.0.0", "--port", "8000"]

networks:
  default:
    name: medical-rag-network
